spring:
  config:
    activate:
      on-profile: dev
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/java_design?serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

  # redis
  data:
    redis:
      host: localhost
      password: 123456
      port: 6379
      database: 0

# 日志
logging:
  level:
    com.clb: debug
    root: info
  pattern:
    dateformat: "yy/MM-dd HH:mm:ss.SSS"
  # 日志写入到文件
#  file:
#    name: book-server.log
#  logback:
#    rolling-policy:
#      max-file-size: 5MB
#      max-history: 3